### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by VladimirCourse** [NAXAM/mapboxnavigationui-android-binding#3]
Can't install Naxam.MapboxNavigationUI.Droid package because of Xbindings.AWSSdk dependencies:

Package Xbindings.AWSSdkPolly.Droid 2.3.8 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package Xbindings.AWSSdkPolly.Droid 2.3.8 supports xamarinandroid10 (Xamarin.Android10,Version=v0.0). 

The same for AWSSdkCore.Droid. Any suggestions how to solve it?

**Comment by tuyen-vuduc** [comment]
@VladimirCourse Have you followed my guide in README?

Others had the same issue with you because not follow my guide.

Plz find the discussion in issue #2

**Comment by VladimirCourse** [comment]
I followed the guide and installed all necessary packages from  https://www.myget.org/F/xbindings/api/v3/index.json source

**Comment by tuyen-vuduc** [comment]
@VladimirCourse Plz don't install packages individually.

You could try out by creating an empty Android project then installing the package. It work definitely well.

If you did install any other NAXAM packages before installing Mapbox Navigation UI package, plz uninstall them all, then install Mapbox Navigation UI. There are some breaking changes on package dependencies.

**Comment by JFDionne** [comment]
@tuyen-vuduc Hi, I got the same error (Package Xbindings.AWSSdkPolly.Droid 2.6.11 is not compatible with monoandroid81)

I'm trying to do it on a xamarin forms, that maybe why? I just tried to install Xbindings.AWSSdkPolly.Droid on a new project, without nothing else

**Comment by tuyen-vuduc** [comment]
There is no issue at my end to install this package either for new project or old one.

Plz make sure your environment up-to-date.

Cheers.

**Comment by JFDionne** [comment]
@tuyen-vuduc Hi, I did, I started a new projet and without nothing I got the same error. I try to install your AWS alone and I got the same error, I think it's because we do it with Xamarin forms 3.
I did a package of your navigation without AWS, it install well, and I add 2 dll by hand.

I tried to check on the source of awssdkpolly.droid, but the url you put on nuget is the package for iOS

**Comment by tuyen-vuduc** [comment]
Hey,

I just checked, the Polly library is already on Nuget.org, no requirement to add our custom feed.

I could install without any issues. A lot of others run without any complains, except you.

Plz make sure you do it correct way.

Cheers.

**Comment by JFDionne** [comment]
@tuyen-vuduc Hi, I thin my bad english make it sound the bad way :)

I see your package is compile for monoandroid81
By nuget.org I mean you didn't put a github for the android version of AWS, the github url for the android version redirect to iOS version.

I trying to install Xbindings.AWSSdkCore.Droid on a fresh install, but I got the same error with android 8.1. It seem to be a "bug", appearing only a few month ago, on version of visual studio only on windows, Mac seem fine.

The solution people tell us to do, is take the package and build it for monoandroid81. But like I told, I can't try it, because your url of github go to the iOS's version and not Android.

**Comment by tuyen-vuduc** [comment]
Hm, just search for it. It's really straight forward to do.

**Comment by JFDionne** [comment]
if I go to https://github.com/xbindings?utf8=%E2%9C%93&q=aws&type=&language=
I only found iOS.

**Comment by tranquvis** [comment]
Hello,
I think @JFDionne is right.
I also can't install the nuget, because `Xbindings.AWSSdkPolly.Droid` is incompatible with monoandroid81.
Since the source of `Xbindings.AWSSdkPolly.Droid` is not on github, I assume it is no longer maintained. 
What is the status of this project and `Xbindings.AWSSdkPolly.Droid`?

**Comment by tuyen-vuduc** [comment]
@tranquvis You couldn't install package Xbindings.AWSSdkPolly.Droid on its own?

**Comment by tranquvis** [comment]
Hello @tuyen-vuduc,

Yes, I didn't find a way to install this package. Also in an empty project.
Did you try it with monoandroid81?

We have now changed to another api, but it might be great to clarify the problem for others.

**Comment by slushpuppy** [comment]
@tuyen-vuduc same issue here
